### ISSUE TITLE
Improper use of require stops `gulp jasmine`

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [pmeskers/lets_javascript#2]
Having `require("some-file-that-does-not-exist")` throws an error that isn't handled well, forcing me to restart `gulp jasmine`

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
```

Farther down:

```
Module not found: Error: Cannot resolve module 'jasmine-react-helpersdsd' in /path/to/file
```

I'd be happy to pair some time with you on this if you're interested :)

**Comment by pmeskers** [comment]
Hey I totally didn't see this until today! In general I haven't yet figured out a reliable way to prevent my gulp watching-tasks (`jasmine`, `dev`, etc..) from crashing when there is a transpiling error, defo keen to solve that. 

I'm out for a few weeks so maybe when I get back I can pick your brain and/or we can pair on this.

cheers

**Comment by MarkyMarkMcDonald** [comment]
Just handled this in our project by using `gulp-prettyerror` to great success. I'll try to put in a pull request later.

Also, I've found https://github.com/pivotal-cf/react-starter and https://github.com/pivotal-cf/pui-react-tools to be other decent sources for configuration example.
